# Generated by Django 3.1.7 on 2023-03-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='core_supervizer',
            options={'verbose_name': 'Супервайзеры', 'verbose_name_plural': 'Супервайзеры'},
        ),
    ]
