# Generated by Django 3.1.7 on 2023-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20230306_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core_supervizer',
            name='region',
            field=models.CharField(choices=[('Чуйская', 'Чуйская'), ('Иссык-кульская', 'Иссык-кульская'), ('Нарынская', 'Нарынская'), ('Джалал-Абадская', 'Джалал-Абадская'), ('Баткенская', 'Баткенская'), ('Ошская', 'Ошская'), ('Таласская', 'Таласская')], max_length=50, verbose_name='Область'),
        ),
    ]
